const tintColor = 'rgba(229, 94, 36, 0.89)';

export default {
  white:"white",
  whiteTransparent:"#FFFFFFAA",
  black:"black",
  transparent:"transparent",
  darkGreen:"#609157",
  transparent:"#ffffff00",
  tintColor,
  cardColor: "white",
  backgroundColor: "#F6F6F6",
  lightBackgroundColor: "white",
  darkBackgroundColor:"#888",
  border: '#cccccc',
  yellowMeniu:"#FEE600",
  yellowMeniuTransparent:"#FEE60055",
  basic:"#3EC9C2",
  premium:"#4ECE4C",
  deluxe:"#E5A002",
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
  facebook: '#3b5998',
  google: '#DD4B39',
};
