const tintColor = 'rgba(229, 94, 36, 0.89)';

export default {
  tintColor,
  black: "black",
  backgroundColor: "#F6F6F6",
  lightBackgroundColor: "white",
  darkBackgroundColor: "#888",
  transparent: "transparent",
  lightOrange: "#FDCF00",
  darkOrange: "#FC8F00",
  lightRed: "#FB3F26",
  darkRed: "#E21001",
  yellowMeniu: "#FEE600",
  yellowMeniuTransparent: "#FEE60055",
  successColor: "#288e11",
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
};
